import Head from "next/head";
import { Inter } from "next/font/google";
import Click from "@/components/Click";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { createTapDetails } from "@/utils/fireConstant";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { userId } = router.query;
  console.log(userId);
  const [tapDetails, setTapDetails] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (userId != null && userId != undefined) {
      const fetchTapDetails = async () => {
        setLoading(true);
        const details = await createTapDetails(userId);
        setTapDetails(details);
        setLoading(false);
      };

      fetchTapDetails();
    }
  }, [userId]);

  return (
    <>
      <Head>
        <title>MiniPanda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div className="fixed inset-0 flex items-center justify-center bg-black">
          <img src="/splash.jpg" alt="Loading" className="w-full h-full object-cover" />
        </div>
      ) : (
        <Click userId={userId} tapDetails={tapDetails} />
      )}
    </>
  );
}
